#che_per_capita - Ivonne Deliany Mondoñedo Mora
```{r}
library(rio)
Linkche_per_capita="https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/Current-health-expenditure-per-capita-current-US.xls"
che_per_capita= import(Linkche_per_capita)
```
#Limpieza
```{r}
che_per_capita[c(2)]=NULL
names(che_per_capita)= c ("Pais", "Porcentaje_che_per_capita")
library(tidyr)

che_per_capita=separate(che_per_capita,Porcentaje_che_per_capita,into=c("Porcentaje_che_per_capita",'delete'), "\\%")[,-3]

che_per_capita[,c(2)]=as.numeric(che_per_capita[,c(2)])

che_per_capita$Porcentaje_che_per_capita=trimws(che_per_capita$Porcentaje_che_per_capita,whitespace = "[\\h\\v]")
```
#Ver los NA's 
```{r}
table(che_per_capita$`Porcentaje_che_per_capita`,useNA = "always")
```
#Merge para quedarnos solo con países de Europa y América 
```{r}
library(rio)
Europa_America2="https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1)%20(6).xls"
EuroAmer2=import(Europa_America2)
names(EuroAmer2)= c ("Pais")
che_per_capita_EA =merge(che_per_capita,EuroAmer2,by.x='Pais', by.y='Pais') 
```



