
```{r}
library(rio)
library(knitr)
library(kableExtra)
lkcorrup='https://github.com/GonzaloBerger/123/raw/master/Data_Extract_From_Worldwide_Governance_control_of_corruption.xlsx'
datacorrup=import(lkcorrup)
```
```{r}
datacorrup[c(2:4)]=NULL
datacorrup=datacorrup[c(1:99),]
```
```{r}
names(datacorrup)=c('Pais','Control de la corrupción')
```
```{r}
datacorrup$`Control de la corrupción`=as.numeric(datacorrup$`Control de la corrupción`)
```
```{r}
lkviolence='https://github.com/GonzaloBerger/123/raw/master/Data_Extract_From_Worldwide_Governance_Indicators_political_stability_and_absence_of_violence.xlsx'
dataviolence=import(lkviolence)
```
```{r}
dataviolence[c(2:4)]=NULL
dataviolence=dataviolence[c(1:99),]
```
```{r}
names(dataviolence)=c('Pais','Estabilidad política y ausencia de violencia/terrorismo')
```
```{r}
dataviolence$`Estabilidad política y ausencia de violencia/terrorismo`=as.numeric(dataviolence$`Estabilidad política y ausencia de violencia/terrorismo`)
```
```{r}
table(datacorrup$`Control de la corrupción`, useNA = 'always')
```
```{r}
table(dataviolence$`Estabilidad política y ausencia de violencia/terrorismo`, useNA = 'always')
```
```{r}
corrupcionyviolencia=merge(datacorrup,dataviolence)
```
```{r}
lkpaises='https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1).xls'
datapaises=import(lkpaises) 
```
```{r}
CorrupcionyViolencia=merge(corrupcionyviolencia,datapaises,all.x=T, all.y=T)
kable(CorrupcionyViolencia[!complete.cases(CorrupcionyViolencia),],type='html')%>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                  font_size = 10)
```
```{r}
CorrupcionyViolencia=merge(datapaises,corrupcionyviolencia)
table(CorrupcionyViolencia$`Control de la corrupción`, useNA = 'always')
table(CorrupcionyViolencia$`Estabilidad política y ausencia de violencia/terrorismo`, useNA = 'always')
```



