
```{r}
library(htmltab)
```
```{r}
library(rio)
```
```{r}
lkpage='https://en.wikipedia.org/wiki/COVID-19_pandemic_by_country_and_territory'
lkpath='//*[@id="thetable"]'
```
```{r}
covid19data=htmltab(doc=lkpage,which = lkpath)
```
```{r}
covid19data[,c(2,4)]=NULL
```
```{r}
lkpage2='https://en.wikipedia.org/wiki/List_of_countries_by_population_(United_Nations)'
lkpath2='//*[@id="main"]'
```
```{r}
population=htmltab(doc=lkpage2,which = lkpath2)
```
```{r}
population[,c(2:4,6)]=NULL
```
```{r}
names(covid19data)=c('Pais','decesos')
```
```{r}
names(population)=c('Pais','poblacion')
```
```{r}
covid19data$Pais=trimws(covid19data$Pais,whitespace = "[\\h\\v]")
```
```{r}
population$Pais=trimws(population$Pais,whitespace = "[\\h\\v]")
```
```{r}
population$Pais=gsub('Â',"",population$Pais)
```
```{r}
population$Pais=trimws(population$Pais,whitespace = "[\\h\\v]")
```
```{r}
Covid19=merge(covid19data,population)
```
```{r}
str(Covid19)
```
```{r}
Covid19$poblacion=gsub(',',"",Covid19$poblacion)
```
```{r}
Covid19$decesos=gsub(',',"",Covid19$decesos)
```
```{r}
Covid19[,c(2:3)]=lapply(Covid19[,c(2:3)],as.numeric)
```
```{r}
str(Covid19)
```


