```{r}
#VARIABLE 1 - ACCOUNTABILITY

library(rio)
lXLSX="https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/Data_From_Worldwide_Governance_Indicators_Voice%20and%20Accountability%20Percentile%20Rank.xlsx"

VoiceandAcc=import(lXLSX)

VoiceandAcc[,c(2,3,4)]=NULL

VoiceandAcc$`2018 [YR2018]`=as.numeric(VoiceandAcc$`2018 [YR2018]`)

table(VoiceandAcc$`2018 [YR2018]`,useNA = "always")

names(VoiceandAcc)=c("Pais","VoiceandAccountability")

library(rio)
lkXLSX = "https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1).xls"
Paisesoficial=import(lkXLSX)

VoiceandAccountability = merge(VoiceandAcc,Paisesoficial,by.x='Pais',by.y='Pais')
```

```{r}
# VARIABLE 2 - CORRUPCION Y VIOLENCIA

library(rio)
lkcorrup='https://github.com/GonzaloBerger/123/raw/master/Data_Extract_From_Worldwide_Governance_control_of_corruption.xlsx'

datacorrup=import(lkcorrup)

datacorrup[c(2:4)]=NULL

datacorrup=datacorrup[c(1:99),]

names(datacorrup)=c('Pais','Control de la corrupción')

datacorrup$`Control de la corrupción`=as.numeric(datacorrup$`Control de la corrupción`)

lkviolence='https://github.com/GonzaloBerger/123/raw/master/Data_Extract_From_Worldwide_Governance_Indicators_political_stability_and_absence_of_violence.xlsx'

dataviolence=import(lkviolence)

dataviolence[c(2:4)]=NULL

dataviolence=dataviolence[c(1:99),]

names(dataviolence)=c('Pais','Estabilidad política y ausencia de violencia/terrorismo')

dataviolence$`Estabilidad política y ausencia de violencia/terrorismo`=as.numeric(dataviolence$`Estabilidad política y ausencia de violencia/terrorismo`)

corrupcion_y_violencia=merge(datacorrup,dataviolence)

lkpaises='https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1).xls'

datapaises=import(lkpaises)

Corrupcion_y_violencia=merge(datapaises,corrupcion_y_violencia)

```

```{r}
#VARIABLE 3 - EFECTIVIDAD DEL GOBIERNO

library(rio)

Gobernabilidad="https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/Data_Extract_From_Worldwide_Governance_Indicators%20(2)%20(1)%20(3).xls"
Gobernabilidad=import(Gobernabilidad)

names(Gobernabilidad)= c ("Pais", "Gobernabilidad")

Gobernabilidad$Gobernabilidad=as.numeric(Gobernabilidad$Gobernabilidad)

table(Gobernabilidad$`Gobernabilidad`,useNA = "always")
```



```{r}
#VARIABLE 4 - IMPERIO DE LA LEY

library(rio)

lkXLSX= "https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/Data_From_Worldwide_Governance_Indicators_Rule%20of%20Law%20Percentile%20Rank.xlsx"

RuleofLaw= import(lkXLSX)

RuleofLaw[,c(2,3,4)] = NULL

RuleofLaw$`2018 [YR2018]`=as.numeric(RuleofLaw$`2018 [YR2018]`)

table(RuleofLaw$`2018 [YR2018]`,useNA = "always")

names(RuleofLaw)=c("Pais","RuleofLaw")

lkXLSX = "https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1).xls"

Paisesoficial=import(lkXLSX)

ImperiodelaLey=merge(RuleofLaw,Paisesoficial,by.x='Pais', by.y='Pais')
```

```{r}
#MERGE 1 - de variable 1 y 2 

Accountability_Corrupcion_y_violencia=merge(Corrupcion_y_violencia,VoiceandAccountability,all.x=T, all.y=T)
```


```{r}
#MERGE 2  - variable 3 y 4 

Gob_Ley=merge(Gobernabilidad,ImperiodelaLey, all.x=T, all.y=T)
```

```{r}
#MERGE DE LA VARIABLE GOBERNANZA - VARIABLES 1, 2, 3 Y 4

Gobernanza=merge(Accountability_Corrupcion_y_violencia,Gob_Ley, all.x=T, all.y=T)
```



