#MERGE ENTRE ACCESO A AGUA POTABLE Y SANEAMIENTO
 
# Limpieza de la base: Acceso a agua potable (Gonzalo Berger)
```{r} 
library(htmltab)
library(tidyr)
library(stringr)
library(rio)
```
```{r}
lkpage='https://www.cia.gov/library/publications/resources/the-world-factbook/fields/361.html'
lkpath='//*[@id="fieldListing"]'
Aguapotable = htmltab(doc = lkpage, which = lkpath)
lkpaises='https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1)%20(6).xls'
datapaises=import(lkpaises) 
Aguapotable = separate(Aguapotable,'Drinking water source',into=c('Z1','Z2'), 'total')
Aguapotable[,c(2)]=NULL
Aguapotable = separate(Aguapotable,'Z2',into=c('Z1','Z2'),'%')
Aguapotable[,c(3)]=NULL
Aguapotable[,c(2)] = gsub(':','',Aguapotable[,c(2)])
Aguapotable[,c(2)] = trimws(Aguapotable[,c(2)],whitespace = '[\\h\\v]')
Aguapotable$Z1=as.numeric(Aguapotable$Z1)
names(Aguapotable)=c('Pais','% of population with access to improved drinking water')
```
# NA
```{r}
table(Aguapotable$`% of population with access to improved drinking water`, useNA = 'always')
```
# Merge
```{r}
Agua=merge(datapaises,Aguapotable)
```

# Saneamiento - Ivonne Deliany Mondoñedo Mora
```{r}
library(htmltab)
Linksana="https://www.cia.gov/library/publications/resources/the-world-factbook/fields/398.html"
Link_path_sana='//*[@id="fieldListing"]'
saneamiento= htmltab (doc = Linksana,which = Link_path_sana)
```
# Limpieza 
```{r}
names(saneamiento)= c ("Pais", "Porcentaje_Saneamiento")
library(tidyr)
saneamiento$Porcentaje_Saneamiento=gsub("\\%.*","",saneamiento$Porcentaje_Saneamiento)
saneamiento$Porcentaje_Saneamiento=gsub(".*\\:","",saneamiento$Porcentaje_Saneamiento)
saneamiento$Porcentaje_Saneamiento=as.numeric(saneamiento$Porcentaje_Saneamiento)
saneamiento$Porcentaje_Saneamiento=trimws(saneamiento$Porcentaje_Saneamiento,whitespace = "[\\h\\v]")
```
# Ver los NA's 
```{r}
table(saneamiento$`Porcentaje_Saneamiento`,useNA = "always")
```
# Merge para quedarnos solo con países de Europa y América 
```{r}
library(rio)
Europa_America1="https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1)%20(6).xls"
EuroAmer1=import(Europa_America1)
names(EuroAmer1)= c ("Pais")
Saneamiento_EA =merge(saneamiento,EuroAmer1,by.x='Pais', by.y='Pais') 
```

# Merge de ambas bases (saneamiento y agua potable) - Mayra Vargas
```{r}
Aguaysaneamiento=merge(Agua,Saneamiento_EA,all.x =T,all.y =T)
Aguaysaneamiento$Porcentaje_Saneamiento=as.numeric(Aguaysaneamiento$Porcentaje_Saneamiento)
```

