#Saneamiento - Ivonne Deliany Mondoñedo Mora
```{r}
library(htmltab)
Linksana="https://www.cia.gov/library/publications/resources/the-world-factbook/fields/398.html"
Link_path_sana='//*[@id="fieldListing"]'
saneamiento= htmltab (doc = Linksana,which = Link_path_sana)
```
#Limpieza 
```{r}
names(saneamiento)= c ("Pais", "Porcentaje_Saneamiento")
library(tidyr)
saneamiento$Porcentaje_Saneamiento=gsub("\\%.*","",saneamiento$Porcentaje_Saneamiento)
saneamiento$Porcentaje_Saneamiento=gsub(".*\\:","",saneamiento$Porcentaje_Saneamiento)
saneamiento$Porcentaje_Saneamiento=as.numeric(saneamiento$Porcentaje_Saneamiento)
saneamiento$Porcentaje_Saneamiento=trimws(saneamiento$Porcentaje_Saneamiento,whitespace = "[\\h\\v]")
```
#Ver los NA's 
```{r}
table(saneamiento$`Porcentaje_Saneamiento`,useNA = "always")
```
#Merge para quedarnos solo con países de Europa y América 
```{r}
library(rio)
Europa_America1="https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1)%20(6).xls"
EuroAmer1=import(Europa_America1)
names(EuroAmer1)= c ("Pais")
Saneamiento_EA =merge(saneamiento,EuroAmer1,by.x='Pais', by.y='Pais') 
```

