
```{r}
library(rio) 
UHClk='https://github.com/GonzaloBerger/123/raw/master/Data_Extract_From_World_Development_Indicators.xlsx'
datauhc=import(UHClk)
```
```{r}
datauhc[,c(1:2,4:13,15:16)]=NULL
datauhc=datauhc[-c(218:269),]
```
```{r}
names(datauhc)=c('Pais','Asistencia sanitaria universal')
```
```{r}
datauhc$`Asistencia sanitaria universal`=as.numeric(datauhc$`Asistencia sanitaria universal`)
```
```{r}
table(datauhc$`Asistencia sanitaria universal`, useNA = 'always')
```



```{r}
lkpaises='https://github.com/IvonneMM/COVID19grupo2oficial/raw/master/America%20y%20Europa3%20(3)%20(1)%20(1).xls'
datapaises=import(lkpaises)
```
```{r}
UHC=merge(datauhc,datapaises,all.x=T,all.y=T,by.x='Pais',by.y='Pais')
```
```{r}
library(knitr)
library(kableExtra)
kable(UHC[!complete.cases(UHC),],type='html')%>%
    kable_styling(bootstrap_options = c("striped", "hover", "condensed", "responsive"),
                  font_size = 10)
```

```{r}
datauhc[datauhc$Pais=='Venezuela, RB','Pais']='Venezuela'
datauhc[datauhc$Pais=='Czech Republic','Pais']='Czechia'
datauhc[datauhc$Pais=='Slovak Republic','Pais']='Slovakia'
datauhc[datauhc$Pais=='Russian Federation','Pais']='Russia'
```
```{r}
UHC=merge(datapaises,datauhc)
```
```{r}
table(UHC$`Asistencia sanitaria universal`, useNA = 'always')
```

